### ISSUE TITLE
Equalizing the images in the comparison tool

### ISSUE THREAD

**Issue by xmha97** [T8RIN/ImageResizer#101]
In the comparison tool, the images must be the same size:

https://user-images.githubusercontent.com/23485114/227066877-1c844e36-3aba-425f-b217-fbbc6b60ac39.mp4

**Comment by T8RIN** [comment]
I don't know, how it should work, because images can be almost different

**Comment by xmha97** [comment]
As you can see in the video, it is comparing a small picture with a large picture.
I think the images should be scaled before comparing like in the VES app.

![Screenshot_2023-03-23-15-21-35-057_com.vincentengelsoftware.vesandroidimagecompare.jpg](https://user-images.githubusercontent.com/23485114/227197533-e1037d98-a166-4a64-ac7a-ede613db315b.jpg)

Suppose an iPhone 4 photo is to be compared with an iPhone 14. The first is 5 megapixels and the second is 50 megapixels
If the images are not the same size, we will not have a correct comparison.

![Screenshot_2023-03-23-15-17-49-358_ru.tech.imageresizershrinker.jpg](https://user-images.githubusercontent.com/23485114/227197593-f7c64a09-18ea-4fba-96d9-6f41bfd0b1f4.jpg)

**Comment by xmha97** [comment]
As you can see in the video, it is comparing a small picture with a large picture.
I think the images should be scaled before comparing like in the VES app.

![Screenshot_2023-03-23-15-21-35-057_com.vincentengelsoftware.vesandroidimagecompare.jpg](https://user-images.githubusercontent.com/23485114/227197533-e1037d98-a166-4a64-ac7a-ede613db315b.jpg)

Suppose an iPhone 4 photo is to be compared with an iPhone 14. The first is 5 megapixels and the second is 50 megapixels
If the images are not the same size, we will not have a correct comparison.

![Screenshot_2023-03-23-15-17-49-358_ru.tech.imageresizershrinker.jpg](https://user-images.githubusercontent.com/23485114/227197593-f7c64a09-18ea-4fba-96d9-6f41bfd0b1f4.jpg)

**Comment by T8RIN** [comment]
Ok, i will try to find solution)

**Comment by xmha97** [comment]
Thanks 🙏
