### ISSUE TITLE
What the airplane icon do??

### ISSUE THREAD

**Issue by Hedronmx** [T8RIN/ImageResizer#12]
I just saw the new paper airplane icon on the top bar, and I'm wondering what it does.... It seems to be some kind of preset?

**Comment by T8RIN** [comment]
Yes it's a preset, which adjust your image extension and size for an telegram sticker, because it is needed to be 512*512 and nave PNG extension

**Comment by NiciTheNici** [comment]
No fucking way you added a preset for exactly the niche application I needed this app for. Youre bloody great man, have a lovely day <3

**Comment by T8RIN** [comment]
Thanks!
