### ISSUE TITLE
[Bugs] no respond when I add image to app

### ISSUE THREAD

**Issue by Nonanne** [T8RIN/ImageResizer#126]
I'm in Android 10 (Xiaomi Mi9 miui12)
Version test: All version in past 14 days ago

when I press add image and select image(s) by android file select. then add to this app but nothing run. no notify, toast message, screen respond. it doesn't crash because I can press add image again and loop.

**Comment by T8RIN** [comment]
Interesting, and even if you try to add image by sharing?

**Comment by T8RIN** [comment]
Also have you had different file pickers available or opens standard immediately?

**Comment by T8RIN** [comment]
Yessss, that's because of second file picker, if you delete it, that would work, i have no idea is it miui 12 fault (because i have that one too), but i've also encountered this weird behavior, i could debug it later, but, picking files is all on the androidx library, i'm just starting activity result launcher, sooo, no ideas for this(( but i'll try to resolve this

**Comment by T8RIN** [comment]
https://forum.xda-developers.com/t/unable-to-upload-files-in-chrome-firefox-using-files-app-in-android-11-miui-12-5.4296623/

Seems to be similar, i will try to disable miui optimisation now

**Comment by T8RIN** [comment]
> > https://forum.xda-developers.com/t/unable-to-upload-files-in-chrome-firefox-using-files-app-in-android-11-miui-12-5.4296623/
> > 
> > ~~Seems to be similar, i will try to disable miui optimisation now~~
> > Doesn't work 
> 
> I think this is my problem cuz I disable miui optimize too. I tried other apps like google drive and it force me to use android file picker. didn't faced any problem with this method.

Maybe this is because i used PickVisualMedia request, but fast forward it is packaged in an android library

**Comment by T8RIN** [comment]
> > > https://forum.xda-developers.com/t/unable-to-upload-files-in-chrome-firefox-using-files-app-in-android-11-miui-12-5.4296623/
> > > 
> > > ~~Seems to be similar, i will try to disable miui optimisation now~~
> > > Doesn't work 
> > 
> > I think this is my problem cuz I disable miui optimize too. I tried other apps like google drive and it force me to use android file picker. didn't faced any problem with this method.
> 
> Maybe this is because i used PickVisualMedia request, but fast forward it is packaged in an android library 

https://developer.android.com/training/data-storage/shared/photopicker
That's one

**Comment by T8RIN** [comment]
Maybe

**Comment by T8RIN** [comment]
I've noticed now, that my another app retrieve image successful in those scenario

**Comment by T8RIN** [comment]
The one diff between them is that i'm using here a newer version of the library, i'will check now

**Comment by T8RIN** [comment]
Nothing, code seems to be the same, but first is returning image, second doesnt

**Comment by T8RIN** [comment]
If you set "use always" when picking, then it works correctly, have no idea, how to fix this :(

**Comment by T8RIN** [comment]
If your device had gms then there is a new photopicker backport down to Android 4.4, i would release it, and the issue will be resolved :) i would close it, if it will not be fixed, you can reopen it 👀
