### ISSUE TITLE
App crash when resizing bigger

### ISSUE THREAD

**Issue by abda11ah** [T8RIN/ImageResizer#13]
Hi,
When i select resize to JPEG + maintain aspect ratio.
If i add more numbers into the width to resize bigger, the app crashes.

![Screenshot_20230223-225047_Image Resizer](https://user-images.githubusercontent.com/1699034/221038848-c151b434-1032-4581-acd5-e3072bdf1a9e.png)

**Comment by T8RIN** [comment]
Which dimensions image had?

**Comment by T8RIN** [comment]
Fixed i think
