### ISSUE TITLE
Custom path display doesn't make a difference between Internal and External Storage

### ISSUE THREAD

**Issue by uli-on** [T8RIN/ImageResizer#136]
I've to say something beforehand: I'm impressed how rapidly this app evolved, how intuitive it can be used and how much more it can do only weeks after it appeared in Izzy's repo. And I love your eye for the details (example: border thickness!) You must be someone who absolutely loves what you're doing!

I could not tell, though, whether I've set my custom path to the external or the device storage, both times the path would be identical: Device Storage/SomeFolder. Both times the images arrive at the correct destination. It's just it's not clear where that is.

**Comment by T8RIN** [comment]
Oh, that's because android just doesn't tell me, where it is located, so i just put translated "device storage" string to start of the shown path :))

Which description will be better, or more clear? 

Also thanks for your nice words, i'm glad that my app can be useful for many people! 👀❤️

**Comment by uli-on** [comment]
The most clear one for "External storage" that I encountered is "SD card", IMO, because it is short and not only names the medium but also describes it. 

And "Internal" would suffice instead of the longish "Internal storage".

**Comment by T8RIN** [comment]
But i can't determine, if it is external or internal storage, because uri contains only a relative path inside the storage, but not a full path :(

**Comment by uli-on** [comment]
Oh, I misunderstood. Unfortunately I can't advice technical stuff. But I discovered that it needs only one more tap on the directory name to look up where exactly files would go. That can suffice as a workaround.

**Comment by uli-on** [comment]
I was using the SAF over the last days only from Image Resizer, and cause SAF remembered the last path I defined here, I thought it would remember it when I returned from using SAF ***anywhere***. But alas, I was wrong, seems it only remembers ***one*** last path, generally, not one path per app.

**Comment by T8RIN** [comment]
Sorry, but what is SAF ?

**Comment by T8RIN** [comment]
I searched everywhere, without my own "device storage" prefix it shows me an empty string if the image was saved in the root package of the storage :(

**Comment by uli-on** [comment]
Sorry from my side :) I never read Android manuals, I only learned from other devs app descriptions: SAF stands for Storage Access Framework, which I interpret(!) as Android's built-in file chooser as it can be encountered in many apps, in situations similar to the one here in Image Resizer when setting the path.

**Comment by T8RIN** [comment]
Oh, got it! Ypu, it shows your path, but because of android limitations (i think) i cannot determine if it is "storage/emulated/0" or "sdcard/" :(

**Comment by locuturus** [comment]
When using a SAF-aware app to open a file it sends the intent:
 `android.intent.action.VIEW` 
and the URI does return the root storage path. Like so:
external -  `content://com.android.externalstorage.documents/document/primary%3ADownload%2FmyFile.mp4`. 
SD card - `content://com.android.externalstorage.documents/document/5E49-697B%3ADownload%2FmyFile.mp4`

I'm curious what is the URI format you get for the `OPEN_DOCUMENT_TREE`? Online examples look something like this: `content://com.android.externalstorage.documents/tree/primary%3Afolder1%2Ffolder2` 
So I would expect the removable SD card URI to look like this:
`content://com.android.externalstorage.documents/tree/5E49-697B%3AuserFolder1%2FuserFolder2`

If I'm right you should be able to search the URI for "primary" or "????-????" to know if the user picked a folder on non-removable external storage (primary storage) or removable storage (has a drive ID). Actually this drive ID could be the SD card or a USB drive. So you might also want to learn the drive ID for the SD card to tell it apart from any attached USB drives.

**Comment by T8RIN** [comment]
Interestingly, looking for the primary keyword is a good idea :)

I will check how to integrate it a bit later , thanks!

**Comment by T8RIN** [comment]
Maybe that would work, check in the next release :)
