### ISSUE TITLE
Offline version

### ISSUE THREAD

**Issue by gl-dev** [T8RIN/ImageResizer#143]
Is it possible to release a version without "Full network access" permission?

**Comment by T8RIN** [comment]
It needed to check updates, however, it isn't used everywhere else, so if you turn the network off, it will work as is!

ImageResizer doesn't collect any of your data, even issue reports

**Comment by gl-dev** [comment]
Was just thinking if it's really necessary, since the Google Play store and F-Droid client do this automatically and full network access just for the reason of update checks seems IMHO a bit of too much permission. But thanks for the clarification.

**Comment by T8RIN** [comment]
I can't get wifi permission in any other way, and i'am using GitHub to check if there is a new release 👀

**Comment by gl-dev** [comment]
Would it be possible to strip the Google/F-Droid version, since the update check is not necessary there?

**Comment by T8RIN** [comment]
Nope
