### ISSUE TITLE
[Feature request] Pipe to Share

### ISSUE THREAD

**Issue by iwilltry42** [T8RIN/ImageResizer#187]
Hey!

It would be amazing if ImageResizer (which works really great btw!) would offer an option to automatically pipe images through for sharing, like e.g. ImagePipe does it.
I.e. I select a few images in the gallery, I click "share", select ImageResizer from the share menu, ImageResizer opens and batch-processes the images (this can be interactive but may use presets as well), then ImageResizer automatically opens the share menu again so I can select any other app to share the images right away (with or **without** saving them locally).

What do you think?

**Comment by T8RIN** [comment]
It is possible already, but without sharing processed images then, so i can simply add share button, which would work without saving images 👀

**Comment by T8RIN** [comment]
I mean, that you can now share any couple of images with image resizer, and batch process them :)

(But yes sharing is unavailable, but thanks, i will try to add this in the future)

**Comment by iwilltry42** [comment]
Yes exactly, batch processing by sharing multiple images to ImageResizer works great.
It's just the second part of sharing resized images from ImageResizer to other apps (instead of saving them).

Looking forward to seeing this feature land here in the future :)

**Comment by T8RIN** [comment]
Yup, I've got it, I will add it in the future 👀

**Comment by T8RIN** [comment]
wait in the 2.0.2 version :)

**Comment by iwilltry42** [comment]
That was fast, amazing!
Thank you!

**Comment by T8RIN** [comment]
you can also test in right now

**Comment by T8RIN** [comment]
[Signed apk (3).zip](https://github.com/T8RIN/ImageResizer/files/11441785/Signed.apk.3.zip)

maybe there are some bugs, i will be glad if you find them

**Comment by zzzzzzxXxzzzzzz** [comment]
> Hey!
> 
> It would be amazing if ImageResizer (which works really great btw!) would offer an option to automatically pipe images through for sharing, like e.g. ImagePipe does it. I.e. I select a few images in the gallery, I click "share", select ImageResizer from the share menu, ImageResizer opens and batch-processes the images (this can be interactive but may use presets as well), then ImageResizer automatically opens the share menu again so I can select any other app to share the images right away (with or **without** saving them locally).
> 
> What do you think?

**Comment by zzzzzzxXxzzzzzz** [comment]
#207

**Comment by T8RIN** [comment]
> #207 

??
