### ISSUE TITLE
feature req. in batch resize

### ISSUE THREAD

**Issue by Wjxfi** [T8RIN/ImageResizer#19]
Now only the first picture is shown in the batch resize

I suggest adding a button that, when clicked, opens a menu with a choice of "which photo to view? There will be the number or names of all the selected photos, clicking on one of them will open this image

This is to check if I resize correctly for each photo

**Comment by T8RIN** [comment]
Thanks for so many suggestions, also will add this as soon as i can

**Comment by T8RIN** [comment]
Thanks for idea, added this, wait in the 1.7.1
