### ISSUE TITLE
[Bug] Chinese is not available since v2.0.0

### ISSUE THREAD

**Issue by Jesse205** [T8RIN/ImageResizer#190]
![Screenshot_20230511_161536_ru.tech.imageresizershrinker.jpg](https://github.com/T8RIN/ImageResizer/assets/51242302/fb5ad777-9b3e-483c-bb0f-25de994b6c45)
![Screenshot_20230511_161541_ru.tech.imageresizershrinker.jpg](https://github.com/T8RIN/ImageResizer/assets/51242302/68fe1e07-c7e3-4c42-8912-f4ce00b51b8d)
![Screenshot_20230511_161548_ru.tech.imageresizershrinker.jpg](https://github.com/T8RIN/ImageResizer/assets/51242302/041da33b-d45c-429c-932b-3e5ea0ce86c3)

**Comment by T8RIN** [comment]
See it :((( will try to fix

**Comment by T8RIN** [comment]
i've fixed i think, can you check on the latest release from actions section?

**Comment by Jesse205** [comment]
![Screenshot_20230511_172813_ru.tech.imageresizershrinker.jpg](https://github.com/T8RIN/ImageResizer/assets/51242302/c800a4f1-3ef0-4aca-b3e3-67f36d39e238)
It's working now
