### ISSUE TITLE
Scrolling stutters

### ISSUE THREAD

**Issue by J43git** [T8RIN/ImageResizer#193]
When I scroll the list in landscape mode, it works fine. But when I scroll in portrait mode, it stutters, almost making me feel like the app will break itself.

**Comment by T8RIN** [comment]
Yes, i found this and fixed it, sorry for that (( fix woll be available in the next release

**Comment by T8RIN** [comment]
Wait for the 2.0.4 :(

**Comment by T8RIN** [comment]
check the new release
