### ISSUE TITLE
Images don't save.

### ISSUE THREAD

**Issue by electr1fy0** [T8RIN/ImageResizer#2]
Tapping the save icon does nothing.

Device: Pixel 7, Android 13.

Also, there's no padding from the bottom navigation bar in the UI. There should be some spacing there.

**Comment by T8RIN** [comment]
Can you send screenshots to my telegram account, or attach them here?

**Comment by electr1fy0** [comment]
I get no feedback when tapping the Save button.
It just makes a loading animation for a split second and nothing happens.

Screenshot:
![Screenshot_20230210-001225](https://user-images.githubusercontent.com/87616300/217907513-7445f023-f8d3-4e08-bc8d-0e9f3842b517.png)

**Comment by T8RIN** [comment]
Thx, will try to fix it right now

**Comment by T8RIN** [comment]
Solved, will upload release now

**Comment by electr1fy0** [comment]
Thanks! I really appreciate this app.

**Comment by T8RIN** [comment]
Thanks!
