### ISSUE TITLE
Cropping an image results in NullPointerException

### ISSUE THREAD

**Issue by adarsh1001** [T8RIN/ImageResizer#201]
Video to showcase the issue:
https://github.com/T8RIN/ImageResizer/assets/8820038/1d3e1d83-49ff-4518-9059-62bf91c40109

Steps to reproduce:
1. Open any image. For reference, I've provided the image used in the above video:
![bdbc9504-2463-4428-8caf-5f817c5c8c6a.jpg](https://github.com/T8RIN/ImageResizer/assets/8820038/cb38dd5a-f32e-4322-8918-1c46609ab4ed)
2. Edit it with ImageResizer.
3. Select Crop.
4. Crop the image however you like, doesn't matter.
5. Hit the Save button.
6. Error.

Error is reproducible even if we open the app first and then import the image.

Device: LG Wing
Android Version: 12
App Version: 2.0.2 (F-Droid)

**Comment by T8RIN** [comment]
Interesting, thanks for the report! Will try to fix this

**Comment by adarsh1001** [comment]
Reinstalling the same app version fixed the issue 🤔 Before that, it was reproducible with every image. Closing this for now.

**Comment by T8RIN** [comment]
I tried it on my android 13 phone now, everything works ok, could you check on the newer version then?

**Comment by T8RIN** [comment]
> Reinstalling the same app version fixed the issue 🤔 Before that, it was reproducible with every image. Closing this for now.

Weird, does it also appear on the 2.0.3?

**Comment by T8RIN** [comment]
> Reinstalling the same app version fixed the issue 🤔 Before that, it was reproducible with every image. Closing this for now.

Feel free to open it again if it repeats :)

**Comment by adarsh1001** [comment]
@T8RIN Tried with both 2.0.2 and 2.0.3, everything is working fine now after fresh installs 😄 Could it have been an older bug maybe related to files permission or some app data that didn't auto resolve with updates?

**Comment by T8RIN** [comment]
Maybe it is associated with permissions, because i didn't touch anything in saving cropped images of a lot of versions

Also i think this can be connected with a new option of changing the output filename, btw thanks for the report!
