### ISSUE TITLE
Exif option

### ISSUE THREAD

**Issue by Baker0o7** [T8RIN/ImageResizer#208]
Hi thanks for your hard work and for making the app kindly if you add exif option removing metadata from image it will be nice thanks

**Comment by T8RIN** [comment]
Sounds interesting to make a special option, but why don't the batch resize with the keep exif option turned off?👀

**Comment by Baker0o7** [comment]
Yah but in my humble opinion it will be batter if you add special option

**Comment by Baker0o7** [comment]
Sorry for asking sir is there any intention of adding image edit in future?

**Comment by T8RIN** [comment]
Okayyyy, then, how should this look? Because I can't imagine this, just a screen with image preview, and save button, or just a count of selected images, idk, really :(

**Comment by T8RIN** [comment]
> Sorry for asking sir is there any intention of adding image edit in future?

Hm, what does it mean?

**Comment by Baker0o7** [comment]
> > Sorry for asking sir is there any intention of adding image edit in future?
> 
> Hm, what does it mean?

Filters

**Comment by Baker0o7** [comment]
> Okayyyy, then, how should this look? Because I can't imagine this, just a screen with image preview, and save button, or just a count of selected images, idk, really :(

Exactly opening the image info deleting metadata(exif)

**Comment by T8RIN** [comment]
> > > Sorry for asking sir is there any intention of adding image edit in future?
> > 
> > Hm, what does it mean?
> 
> Filters 

Maybe, there already were feature requests for some kind of that, but now i don't have enough time to implement new features, just fixing something, the filters can be implemented in the july i think

**Comment by T8RIN** [comment]
> > Okayyyy, then, how should this look? Because I can't imagine this, just a screen with image preview, and save button, or just a count of selected images, idk, really :(
> 
> Exactly opening the image info deleting metadata(exif)

That needed to be a batch option of course, What I want to say is that there will be no controls on the screen, there will be a lot of free space ...

**Comment by Baker0o7** [comment]
> > > > Sorry for asking sir is there any intention of adding image edit in future?
> > > 
> > > Hm, what does it mean?
> > 
> > Filters 
> 
> Maybe, there already were feature requests for some kind of that, but now i don't have enough time to implement new features, just fixing something, the filters can be implemented in the july i think

Sure sir take your time

**Comment by T8RIN** [comment]
> > Okayyyy, then, how should this look? Because I can't imagine this, just a screen with image preview, and save button, or just a count of selected images, idk, really :(
> 
> Exactly opening the image info deleting metadata(exif)
> 
> Kinda like this app you will find the idea
> 
> https://github.com/SimpleMobileTools/Simple-Gallery

Will add this as soon as i get free time, btw, report issues if you find them, i will try to resolve them as fast as i can :)

**Comment by Baker0o7** [comment]
> > > Okayyyy, then, how should this look? Because I can't imagine this, just a screen with image preview, and save button, or just a count of selected images, idk, really :(
> > 
> > Exactly opening the image info deleting metadata(exif)
> > 
> > Kinda like this app you will find the idea
> > 
> > https://github.com/SimpleMobileTools/Simple-Gallery
> 
> Will add this as soon as i get free time, btw, report issues if you find them, i will try to resolve them as fast as i can :)

 Sure sir I'll
