### ISSUE TITLE
feature req. jpg support (not jpeg)

### ISSUE THREAD

**Issue by Wjxfi** [T8RIN/ImageResizer#21]
This is a very popular format that my camera works with

**Comment by T8RIN** [comment]
Will try to add this soon 👀

**Comment by T8RIN** [comment]
Jpeg is only the compress format, images although saved with .jpg extension

**Comment by T8RIN** [comment]
I can add jpeg/jpg output file type picking to make it more clear

**Comment by T8RIN** [comment]
Added :)
