### ISSUE TITLE
When an image is selected, no image is displayed(received) in the app

### ISSUE THREAD

**Issue by Super12138** [T8RIN/ImageResizer#215]
# Steps to reproduce
1. Open app
2. Choose any tool
3. Select an image
4. Show the bug

# System info
HarmonyOS 3 (Android 10)

# Resources
Here is a video ⬇️
<video src="https://github.com/T8RIN/ImageResizer/assets/70494801/2ec32ccd-d624-4ddd-8f0d-0d6b65353b2f"></video>

**Comment by T8RIN** [comment]
That's an android bug :( if you select this file explorer to be opened every time, then this would work...

**Comment by T8RIN** [comment]
Check #126

**Comment by Super12138** [comment]
> Check #126

You are right, using the share menu import is useful

**Comment by Super12138** [comment]
> That's an android bug :( if you select this file explorer to be opened every time, then this would work...
Maybe you can use the gallery api to choose the image, maybe it isn't has this problem

**Comment by T8RIN** [comment]
> > That's an android bug :( if you select this file explorer to be opened every time, then this would work...
> 
> Maybe you can use the gallery to choose the image, maybe it can solve this problem.
> 
> Like this:
> ![Example](https://github.com/T8RIN/ImageResizer/assets/70494801/600b3632-9338-497c-921e-0ab703dd8fa9)
> 
> 
> 
> 

Maybe, but i'm using an integrated photopicker and get content result launchers, i can try to add a switch to select one of this options

**Comment by T8RIN** [comment]
Added that

**Comment by Super12138** [comment]
In addition, this bug will appear when you use this app, lock screen, and open it.
