### ISSUE TITLE
Implement AI super resolution scalers

### ISSUE THREAD

**Issue by he2a** [T8RIN/ImageResizer#22]
I was wondering if there's any chance to include AI super resolution scalers like Waifu2x, RealSR, etc. for upscaling images? These scalers can work if there's Vulcan support and binaries can be found [here](https://github.com/tumuyan/RealSR-NCNN-Android).

**Comment by T8RIN** [comment]
Unfortunately no, the size of app will increase 100 times accordingly :(

**Comment by Toiletmason** [comment]
@T8RIN Please reconsider this. It's the only thing the app is missing. SuperImage exists, but has been moved to close source.

**Comment by T8RIN** [comment]
I heard about super image, that's really bad that it went for money way, but, i'll not add this because app size will be increased 10 times
