### ISSUE TITLE
Naming convention for result files

### ISSUE THREAD

**Issue by Runner86** [T8RIN/ImageResizer#228]
- Tested feature: General settings - Filename

- Use case: set prefix for converted file(s) and process one or more.

- Oberserved result: the resulting filename(s) follow a pattern like <prefix><date>_<time>_<random_seq_num>

- Expected result: the result files should have a more user friendly naming like <prefix>_<original_filename> or <original_filename>_<suffix>

**Comment by T8RIN** [comment]
That's not a random sequence :)
It is datetime with year month day hour minute secs and millisecs 😼

**Comment by T8RIN** [comment]
And i'm not sure what you don't like :(

**Comment by T8RIN** [comment]
Option to add the original filename in the output image?

**Comment by Runner86** [comment]
O yeah, adding the original filename optional as suffix to the file name of the output image ist helpful (additional to the Prefix).

If there would be an 2nd option ;-) to replace the "date_time" by a "sequence_number" (3 digit, starting with 000) the most use cases might be well covered.

**Comment by T8RIN** [comment]
Added this by two options
