### ISSUE TITLE
Rename algorithm from v2.0.3 is very bad

### ISSUE THREAD

**Issue by Perlover** [T8RIN/ImageResizer#233]
Hello,

Started from v2.0.3 (and v2.0.4 current) your app does a very bad renaming during a batch resizing (strange names and lost extensions) . Example: https://nostr.build/p/nb9253.jpg

This began when you added the option "Prefix" for images.

And always a warning dialog about exit from current stage is very very annoyed :(((

**Comment by T8RIN** [comment]
Я просто подумал, что рандомный набор цифр в конце выглядит не очень, поэтому там теперь год, месяц, день, час, минута, секунда и миллисекунда сохранения.
Чтобы вот такого не было, когда файлы в одно время сохраняются и накладываются друг на друга я раньше использовал рандомный набор цифр, но, тут меня уже попросили, добавил настройку, чтобы была возможность заменить дату на порядковый номер сохранения, если используется пакетная обработка :)

А вообще наверное стоит секунды и миллисекунды обратно на хешкод поменять, ибо раньше такого быть не могло

**Comment by Perlover** [comment]
Честно говоря, я не понимаю, чем простой счётчик мешает создавать правильные имена? Пакетная обработка происходит в параллельных нитях? Если так, можно использовать семафоры вместе со счётчиком, чтобы нумерация не накладывалась. К тому же имена файлов не очень то похоже на те, что созданы через использование простого счётчика. Такое ощущение, что там просто время в соседних миллисекундах

**Comment by T8RIN** [comment]
Да, в старой версии то так, в новой вот там есть счетчик

**Comment by T8RIN** [comment]
> Честно говоря, я не понимаю, чем простой счётчик мешает создавать правильные имена? Пакетная обработка происходит в параллельных нитях? Если так, можно использовать семафоры вместе со счётчиком, чтобы нумерация не накладывалась. К тому же имена файлов не очень то похоже на те, что созданы через использование простого счётчика. Такое ощущение, что там просто время в миллисекундах

Синхронно, но настолько быстро, что одинаковое время возможно

**Comment by Perlover** [comment]
> > Честно говоря, я не понимаю, чем простой счётчик мешает создавать правильные имена? Пакетная обработка происходит в параллельных нитях? Если так, можно использовать семафоры вместе со счётчиком, чтобы нумерация не накладывалась. К тому же имена файлов не очень то похоже на те, что созданы через использование простого счётчика. Такое ощущение, что там просто время в миллисекундах
> 
> Синхронно, но настолько быстро, что одинаковое время возможно 

Тогда в чем проблема использовать нумерацию через обычный инкремент переменной?

**Comment by T8RIN** [comment]
В последней версии все так и есть, повторюсь 👀

**Comment by Perlover** [comment]
> В последней версии все так и есть, повторюсь 👀
 
Этот баг я заметил в 2.0.4, затем я удалил и стал ставить ступенчато и нашел, что баг начинается с версии 2.0.3. Версия 2.0.4 у вас последняя на github. Я устанавливал версии из F-Droid

**Comment by T8RIN** [comment]
Я про 2.0.5

**Comment by T8RIN** [comment]
Не релизнул ее пока

**Comment by Perlover** [comment]
Теперь понятно. Я ведь не компилирую из текущих исходников :)

**Comment by T8RIN** [comment]
Апк скомипленный есть уже, можно в actions скачать👀
