### ISSUE TITLE
Preference Item Icons are not centred.

### ISSUE THREAD

**Issue by Iamlooker** [T8RIN/ImageResizer#24]
Preference Item Icons are not centred as shown in screenshot

<details>
<summary>Details</summary>

![photo_2023-03-01_01-31-49](https://user-images.githubusercontent.com/60404093/221965623-c07b2e5c-e9de-4196-979d-478c3033cdf6.jpg)

</details>

**Comment by Iamlooker** [comment]
I would like to make a PR to fix this

**Comment by T8RIN** [comment]
I did this especially for the icon and title to be on the same level 👀

**Comment by T8RIN** [comment]
Why do you don't like this appearance?

**Comment by Iamlooker** [comment]
According to me when a visual element is not very tall, the content should be centred. This makes the UI more consistent.

**Comment by T8RIN** [comment]
Let's assume that this is my author's wish)

**Comment by Iamlooker** [comment]
Cool, will close the issue then 😄

**Comment by T8RIN** [comment]
Feel free to write again, if you found something improve in the future 👀

**Comment by Iamlooker** [comment]
Sure sure 🫡
