### ISSUE TITLE
Compare when edit (resizing)

### ISSUE THREAD

**Issue by srcarkk** [T8RIN/ImageResizer#241]
In the resizing tab, there could be an option to compare the image before and after, it may be my freshness but, in my opinion, it is very practical to not be generating many images to find the perfect one, and it is only necessary to compare during the resizing.

**Comment by T8RIN** [comment]
![Screenshot_20230527-062404_Image Resizer.png](https://github.com/T8RIN/ImageResizer/assets/52178347/6fefee54-4e63-42b2-a001-e3de7964e2d9)

Tap and hold this👀

**Comment by srcarkk** [comment]
> ![Screenshot_20230527-062404_Image Resizer.png](https://github.com/T8RIN/ImageResizer/assets/52178347/6fefee54-4e63-42b2-a001-e3de7964e2d9)
> 
> Tap and hold this👀

![Screenshot_20230527082316.jpg](https://github.com/T8RIN/ImageResizer/assets/82451852/6bb47cd0-c9a0-4feb-8b1e-56483ff6f713)


Yeah, I know, but I just wanted the comparison tab, not to replace it, but just to implement it in the resizing tab, because that way I could see the quality of the photo SIDE BY SIDE.

**Comment by T8RIN** [comment]
Oh, got it, i will add this later by modal sheet (same as zooming implemented) :)

**Comment by srcarkk** [comment]
> Oh, got it, i will add this later by modal sheet (same as zooming implemented) :)

Ok, thanks 😃👍

**Comment by T8RIN** [comment]
done
