### ISSUE TITLE
Internet permission

### ISSUE THREAD

**Issue by davidmef** [T8RIN/ImageResizer#245]
According to https://f-droid.org/es/packages/ru.tech.imageresizershrinker/ it needs full access to the internet. What does the application need the internet permission for?

**Comment by T8RIN** [comment]
Check #143

**Comment by davidmef** [comment]
Some Android developers explain in the README or the documentation why their application uses the permissions. If you did this, you will avoid questions like mine. :)

**Comment by T8RIN** [comment]
Will think about it, thanks :)
