### ISSUE TITLE
(user help) More detailed information about processing modes

### ISSUE THREAD

**Issue by Runner86** [T8RIN/ImageResizer#247]
Version: 2.0.5 (61)
Feature: Batch resize
Use case: load sveral images with different size orientaion and aspect ratio.
The following link leads to a zip archive with suitable test images:
https://c.gmx.net/@334287797445728069/5qK2XbdHRNeEy_QitP5K_g

Suggest to provide more detailed information about the processing modes to the user.
For example (as far as I understand):

**Expilcit**
(i) Forces every picture into an image give by the Width and Height parameter - may change aspect ratio

**Flexible**
(i) Resizes pictures to images with a long side given by the Width parameter - keeps aspect ratio

**Ratio**
(i) ...... (I'm not clear about this)

**Comment by T8RIN** [comment]
Let me explain, Flexible = Ratio, but if you use ratio mode, width in the width field will be changed accordingly to the real output image size

**Comment by Runner86** [comment]
Thank's !
However I suggest to integrate an explanation for all 3 options as a kind of help function into the next version to let all users participate on this knowledge.
Anyway, I would recommend to make a test with all the images metioned above in one batch run - You'll see that in Ratio mode the sizes of some result files differ from the entries in the width/height field.
