### ISSUE TITLE
app unusable, can't get past permission popup

### ISSUE THREAD

**Issue by muchqs** [T8RIN/ImageResizer#249]
Android 9
v2.0.5 from f-droid

Upon start, it asks to grant storage permission, even though it was already granted. I click on Allow, nothing happens. Then click on Allow a few more times, app says "this permission must be granted for app to work" and opens the app permission settings system screen. But again, it's already granted. Return to the app, it still asks to grant the permission therefore unable to even get to the main app screen to use the app.

Tried clear cache and app data. Also tried uninstall and reinstall clean. Nothing helped.

Went back to v2.0.4, everything works properly.

**Comment by T8RIN** [comment]
Terrible ((( Thanks for the report, I think I know what the problem is ... Will fix it as soon as possible
