### ISSUE TITLE
Show as image editor

### ISSUE THREAD

**Issue by xmha97** [T8RIN/ImageResizer#25]
Hi, I can't see this app as an image editor.
I want to use your app to crop my photos.
Please fix this issue.
Thanks 🙏

![Screenshot_2023-03-03-02-30-46-561_deckers.thibault.aves.jpg](https://user-images.githubusercontent.com/23485114/222579529-1a14d03b-6a2c-46e6-a3e8-93ee9feccdbe.jpg)

![Screenshot_2023-03-03-02-31-15-761_android.jpg](https://user-images.githubusercontent.com/23485114/222579538-d9752325-e6b3-402c-801e-638b6f44a2b7.jpg)

**Comment by T8RIN** [comment]
Thanks, will add this feature :)

**Comment by T8RIN** [comment]
Added :)

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by T8RIN** [comment]
Wait for the next release 👀

**Comment by xmha97** [comment]
> Wait for the next release 👀

Can't wait 🤩
