### ISSUE TITLE
UI for flexible scaling

### ISSUE THREAD

**Issue by uli-on** [T8RIN/ImageResizer#252]
I'm a little desperate about the translation for `Resizes pictures to images with a long side given by the Width parameter` and want to find out what I can do about it. While testing this setting it seems to turn out that the value for width defines the max side length, be the image a landscape or a portrait format, regardless. Wouldn't it be easier to understand/to use/to translate, if the field for height would be invisible when flexible scaling is chosen? It seems to have no influence. Or have I somehow managed to misinterpret the outcome of my tests?

**Comment by T8RIN** [comment]
I did not describe correctly, in fact it depends on both the width and the height 👀

**Comment by T8RIN** [comment]
I did not describe correctly, in fact it depends on both the width and the height 👀

**Comment by T8RIN** [comment]
I will fix it when weblate maintenance works finish 👀

**Comment by T8RIN** [comment]
Changed
