### ISSUE TITLE
Add a facility to compress the image to a specific size

### ISSUE THREAD

**Issue by GET100PERCENT** [T8RIN/ImageResizer#26]
It will be helpful if an option to compress the image to a specific size (in MB, KB) has been implemented.

**Comment by T8RIN** [comment]
I think it should be an another option of image editing, like color picking, right? Because for now editor overloaded

**Comment by GET100PERCENT** [comment]
most sites limits the size of image to be uploaded in online forms "the image should be less than 100kb", "passphoto should be less than 30kb","signature should be less than 10kb" etc.

**Comment by GET100PERCENT** [comment]
> I think it should be an another option of image editing, like color picking, right? Because for now editor overloaded

Okay, I will wait.

**Comment by T8RIN** [comment]
> most sites limits the size of image to be uploaded in online forms "the image should be less than 100kb", "passphoto should be less than 30kb","signature should be less than 10kb" etc.
> 

Yes, i'm understand, will add this :)
