### ISSUE TITLE
Aspect ratio

### ISSUE THREAD

**Issue by xmha97** [T8RIN/ImageResizer#28]
Please add the support aspect ratio for cropping pictures. (Like the Snapseed app)

![IMG_20230303_161124_372.jpg](https://user-images.githubusercontent.com/23485114/222723489-5d13ef5a-1bd7-42fd-a46f-476476db1fd0.jpg)

**Comment by T8RIN** [comment]
Will try to add this as soon as i can

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by T8RIN** [comment]
Done

**Comment by xmha97** [comment]
Thanks 🙏
Please release a version. 🤩

**Comment by T8RIN** [comment]
Will be soon

**Comment by xmha97** [comment]
Thanks 🙏
