### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by IzzySoft** [T8RIN/ImageResizer#3]
While your app is already [listed in my repo](https://apt.izzysoft.de/fdroid/index/apk/ru.tech.imageresizershrinker), someone opened an [inclusion request with F-Droid](https://gitlab.com/fdroid/rfp/-/issues/2364) – where issuebot complained about missing fastlane structures. With your app listed in my repo I have already set them up. Originally I wanted to provide them to you via a PR, but Gihub is currently stuck when trying to fork – so find the files attached below.

Simply unzip the archive to your repo's root, then add and commit the changes. Be welcome to update the description, replace the screenshots, add a featureGraphic, add per-release changelogs, additional locales – as you wish: it's yours :smiley: Be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance.

[fastlane.zip](https://github.com/T8RIN/ImageResizer/files/10716020/fastlane.zip)

Btw: that "someone" (literally: "Somebody") ticked the box of having you (the author of this app) informed and stating you're not opposed to inclusion, so you're probably aware already.

**Comment by T8RIN** [comment]
Somebody it is me, i will add this soon, thx!

**Comment by IzzySoft** [comment]
So I should have phrased it like the usual "password change request" mails I receive from Wikipedia every now and then when someone tries to steal my account: "Somebody, probably you, …"? :see_no_evil:

Thanks!

**Comment by T8RIN** [comment]
Done!

**Comment by IzzySoft** [comment]
Now that it's live at F-Droid I usually drop it from my repo after a decent overlap (about 2 weeks) – unless explicitly asked to keep it. As you achieved reproducible builds (congrats!), cross-updates are possible, so existing users should be seamlessly switched over. That OK with you? As your app isn't too big… well, RB also works the other way should updates get stuck :wink: So I leave the decision to you.

**Comment by T8RIN** [comment]
Can you keep it , please?👀

**Comment by IzzySoft** [comment]
Marked for keep then, so my dupe-checker no longer reports it (and my web front-end will show it accordingly after the next sync).

**Comment by T8RIN** [comment]
Thanks!

**Comment by TPS** [comment]
@IzzySoft I think your repo is pulling the wrong _(`x86_64`)_ binary.

**Comment by T8RIN** [comment]
@IzzySoft i've some questions by #412 👀

**Comment by IzzySoft** [comment]
Just found them, and hopefully answered them all (with my last edit). If there were any left, just raise them and I see that I answer them as well.

**Comment by T8RIN** [comment]
Did it 👀
