### ISSUE TITLE
Remove the exit message box

### ISSUE THREAD

**Issue by xmha97** [T8RIN/ImageResizer#30]
Please remove the exit message box.

![Screenshot_2023-03-03-16-21-09-717_ru.tech.imageresizershrinker.jpg](https://user-images.githubusercontent.com/23485114/222724891-b4b62c05-c161-49bb-a810-3c31383a7f9f.jpg)

Thanks 🙏

**Comment by T8RIN** [comment]
Why?

**Comment by xmha97** [comment]
Because I am not comfortable at all and I think this message is redundant.

https://user-images.githubusercontent.com/23485114/222732063-5c6334a0-af9b-4086-aaef-4f08951a890c.mp4

**Comment by T8RIN** [comment]
I will think, but for now i want to keep it 👀

**Comment by xmha97** [comment]
You can add an option to hide it.

**Comment by T8RIN** [comment]
I can disable it for cases when you entering the app through intent i think :)

**Comment by T8RIN** [comment]
Added this, if you share or edit then exit will not be shown

**Comment by xmha97** [comment]
> Added this, if you share or edit then exit will not be shown

Thanks 🙏
It's very good.
