### ISSUE TITLE
Save Location

### ISSUE THREAD

**Issue by ripsivis** [T8RIN/ImageResizer#32]
Resized images appears on Camera folder of Google Photos because images saved under a subfolder in `/sdcard/DCIM`. Could you move the subfolder to `/sdcard/Pictures` ?

**Comment by T8RIN** [comment]
I'll try if it doesn't break the save

**Comment by T8RIN** [comment]
I'll try if it doesn't break the save

**Comment by T8RIN** [comment]
I thought about it, and i will add fascility to pick output folder manually i think
