### ISSUE TITLE
feature request: Resize image in cm or mm

### ISSUE THREAD

**Issue by Rushik1998** [T8RIN/ImageResizer#33]
Hello....Is it possible to add Resize option in cm or mm. Resizing in pixel is great but most of online application requires images to be in cm or mm.Thanks

**Comment by T8RIN** [comment]
Will think 🤔

**Comment by T8RIN** [comment]
Tried, this works really unstable, because conversion from px to cm not dencity independent transformation

**Comment by Rushik1998** [comment]
Thank you for yours efforts.
