### ISSUE TITLE
Bad rendering of translated text in top app bar

### ISSUE THREAD

**Issue by lorenzovngl** [T8RIN/ImageResizer#34]
I'm working on Italian translation (#31) and I noticed that in the [Batch Resize activity](https://github.com/T8RIN/ImageResizer/blob/master/app/src/main/java/ru/tech/imageresizershrinker/batch_resize/BatchResizeScreen.kt) the English title fits perfectly, while the French and the Italian strings, which are longer, overflows.
<table>
<tr>
<td>
<img width="200px" src="https://user-images.githubusercontent.com/13767301/222957604-79ecd886-887c-4edb-baf2-52063fa35adf.png">
<br>Default language (English)
</td>
<td>
<img width="200px" src="https://user-images.githubusercontent.com/13767301/222957615-987e61f9-6551-4b87-acb5-4beb9af3225c.png">
<br>French
</td>
<td>
<img width="200px" src="https://user-images.githubusercontent.com/13767301/222957853-4c856d92-b69f-4968-9078-d7c0c1b6019d.png">
<br>Italian
</td>
</tr>
</table>

I came up with two possible solutions:
- In the composable function, set a text size smaller than the default language for French and Italian, something like this:
```
if (app is using the default language){
    // Render text in the default size
} else if (app is using the French translation) {
    // Render the text optimally for French strings (maybe with a small text size)
} ...
```
- Apply a marquee behavior to the text that overflows.

Also I got suggestions [here](https://twitter.com/pranavpandeydev/status/1632135739139055617) and [here](https://twitter.com/max_keppeler/status/1632124385308934145).

**Comment by T8RIN** [comment]
Maybe it will better to scale the font, until it perfectly fits in? Or use marquee, it is also possible solution, i think

**Comment by T8RIN** [comment]
Fixed

**Comment by lorenzovngl** [comment]
Thank you!
