### ISSUE TITLE
Error while opening an image

### ISSUE THREAD

**Issue by GET100PERCENT** [T8RIN/ImageResizer#35]
When opening an image, i got the following error:
![Screenshot_20230306-001240](https://user-images.githubusercontent.com/116144024/222979606-c3938d91-d529-4a83-837b-aa4339f79d8e.jpg)

**Comment by T8RIN** [comment]
You are trying to open 132 mb image, it is too large to open on your device

**Comment by GET100PERCENT** [comment]
Looks like the same problem as previous one?

**Comment by T8RIN** [comment]
> Looks like the same problem as previous one?

I think yes, which device do you have?

**Comment by GET100PERCENT** [comment]
> > Looks like the same problem as previous one?
> 
> I think yes, which device do you have?

Samsung galaxy on 5 pro
