### ISSUE TITLE
Improve the crop feature 

### ISSUE THREAD

**Issue by xmha97** [T8RIN/ImageResizer#37]
Please improve the crop feature.
I can change the aspect ratio when I locked it.

https://user-images.githubusercontent.com/23485114/223445676-df455415-9901-4d84-af1d-9e7a92c9175e.mp4

Snapseed is working fine:

https://user-images.githubusercontent.com/23485114/223445791-d0725d27-dfbf-4769-8be4-bd5c05de7174.mp4

**Comment by T8RIN** [comment]
I think it is okay, so intended behavior i think

**Comment by T8RIN** [comment]
fixed

**Comment by xmha97** [comment]
Thanks 🙏
