### ISSUE TITLE
[BUG] App crashes on image save

### ISSUE THREAD

**Issue by HarriBuh** [T8RIN/ImageResizer#38]
> java.lang.NullPointerException
java.lang.NullPointerException
	at s6.c.a(SourceFile:168)
	at ru.tech.imageresizershrinker.main_screen.t.Z(SourceFile:19)
	at q6.b$a.j(SourceFile:135)
	at o4.a.s(Unknown Source:8)
	at f5.i0.run(Unknown Source:100)
	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:79)
	Suppressed: f5.g0: [l1{Cancelling}@832c9f8, Dispatchers.Main.immediate]<

This issue happens permanently, every time I'm trying to save a size-reduced image.

**Comment by T8RIN** [comment]
Additional info? Android, steps to reproduce

**Comment by HarriBuh** [comment]
Google Pixel 7
Android 13, root

Steps to reproduce:
1. Open App
2. Open image
3. Select desired quality
4. Press save button

**Comment by HarriBuh** [comment]
I managed to "fix" the issue by manually resetting the app (clear cache and storage).

**Comment by HarriBuh** [comment]
Nope. Not yet.

**Comment by T8RIN** [comment]
What happened before you spotted this issue? Selected new saving path and then?

**Comment by T8RIN** [comment]
> ~~Nope. Not yet.~~
> 
> ~~Yes I did. Since the issue does not occur again since my app reset, I won't be able to reproduce the issue any longer - for now.~~
> 
> The issue seems to be related to deleting the exif data of any image prior to any further steps.
> I just did it and the error / crash is happening again.
> Even if I closed the app completely (via app manager > force stop) and then edit any image again, the crash persists.

Hmm, interesting, will check soon

**Comment by T8RIN** [comment]
Weird, on Emulator with android 13 everything works as expected...

**Comment by T8RIN** [comment]
Does this apply to all images or just one?

**Comment by T8RIN** [comment]
Does this apply to all images or just one?

**Comment by HarriBuh** [comment]
Every image. Like I said, I can 100% confirm the crash always happens after performing the exif data deletion, on any random image. The process itself seems to trigger it.

**Comment by T8RIN** [comment]
Interesting, will check it again

**Comment by T8RIN** [comment]
Can you check it on this unminified apk and send log, so i will be able to find where issue occures

**Comment by T8RIN** [comment]
Hello, had you found the issue?

**Comment by HarriBuh** [comment]
I'm very sorry, but I haven't been able to reproduce it lately - that's weird, as it happened in 9/10 attempts before.

**Comment by T8RIN** [comment]
Interesting, will wait for updates 👀

**Comment by HarriBuh** [comment]
You may as well close this ticket for now. I can reopen it once this bug happens again.

**Comment by T8RIN** [comment]
Ok, thanks!
