### ISSUE TITLE
Share an image or group of images with Image Resizer App

### ISSUE THREAD

**Issue by AlbahrawyTiger** [T8RIN/ImageResizer#4]
Is it possible to add feature Share an image or group of images with Image Resizer app to change the qualit?

**Comment by T8RIN** [comment]
> Is it possible to add feature Share an image or group of images with Image Resizer app to change the qualit? 

Done, wait for the next release :)

**Comment by T8RIN** [comment]
check the 1.4 release :)

**Comment by T8RIN** [comment]
This will be added, when i I will reach batch resize feature, stay tuned 👀
