### ISSUE TITLE
Add ability to retain aspect ratio

### ISSUE THREAD

**Issue by Hedronmx** [T8RIN/ImageResizer#5]
It would be nice to have a lock ration button so we can resize images without distorting them

**Comment by T8RIN** [comment]
> It would be nice to have a lock ration button so we can resize images without distorting them 

These feature exists, just use flexible resize type! :)

**Comment by Hedronmx** [comment]
Would it be possible then , to update either the width or the height to show that the aspect has been retained?

Example if I have an image of resolution 200x100 and I want to resize to 100 width, then the height should change to 50 automatically. I have attached a screenshot of a test I did

![Screenshot_20230218-014254_Image Resizer](https://user-images.githubusercontent.com/26935602/219853611-405275f4-76a6-4937-b8e4-a707e50f6013.png)

Thank you so much

**Comment by T8RIN** [comment]
Ok, i'll fix this in the next release :)
Also you can star repo to support my work 👀

**Comment by T8RIN** [comment]
Added ratio resize as another option
