### ISSUE TITLE
[New Tool] Comparison (Overlay Slide)

### ISSUE THREAD

**Issue by xmha97** [T8RIN/ImageResizer#54]
Please add the Comparison tool (like VES app):

https://github.com/VincentEngel/VES-Image-Compare

https://user-images.githubusercontent.com/23485114/224507313-294e7252-8aec-4511-8ff2-1ffe357848ce.mp4

**Comment by T8RIN** [comment]
Ok, will try

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by xmha97** [comment]
Thanks 🙏
Please release a version.
