### ISSUE TITLE
[New Tool] Comparison (Side by Side)

### ISSUE THREAD

**Issue by xmha97** [T8RIN/ImageResizer#55]
Please add the Comparison tool (like VES app):

https://github.com/VincentEngel/VES-Image-Compare

https://user-images.githubusercontent.com/23485114/224508689-c0c1b340-8578-4539-bb48-dc000b428d47.mp4

**Comment by T8RIN** [comment]
Resolved in (#54)

**Comment by xmha97** [comment]
Thanks for #55

![Screenshot_2023-03-12-06-03-37-847_ru.tech.imageresizershrinker.jpg](https://user-images.githubusercontent.com/23485114/224520954-3e176f46-78e4-4e4e-bac8-fd9b64be1578.jpg)

Please add this feature request.
I can't find it on the app.

**Comment by xmha97** [comment]
Hi @T8RIN 
Thanks for #54
![Screenshot_2023-03-12-06-03-37-847_ru.tech.imageresizershrinker.jpg](https://user-images.githubusercontent.com/23485114/224520954-3e176f46-78e4-4e4e-bac8-fd9b64be1578.jpg)

Please add this feature request.
I can't find it on the app.
Thanks 🙏

**Comment by T8RIN** [comment]
But it also the same, you also can zoom in my implementation

**Comment by xmha97** [comment]
Thanks 🙏
