### ISSUE TITLE
Add "Compare" item on sharing photos.

### ISSUE THREAD

**Issue by xmha97** [T8RIN/ImageResizer#57]
Hi,
Please add "Compare" item on sharing photos.

![Screenshot_2023-03-12-06-10-01-297_android.jpg](https://user-images.githubusercontent.com/23485114/224521222-441b37f0-b07a-4da9-928f-5976e3715d72.jpg)

![Screenshot_2023-03-12-06-10-06-237_ru.tech.imageresizershrinker.jpg](https://user-images.githubusercontent.com/23485114/224521224-4d37655c-5556-4c73-a9ce-142e55478233.jpg)

**Comment by T8RIN** [comment]
Will add 👀

**Comment by T8RIN** [comment]
Also added zoom to comparing

**Comment by xmha97** [comment]
Thanks 🙏
