### ISSUE TITLE
PNG extension 

### ISSUE THREAD

**Issue by alabotski** [T8RIN/ImageResizer#6]
When I choose PNG extension image compression doesn't work
Why?

For example 
https://github.com/caydey/ffshare

Works with png

**Comment by T8RIN** [comment]
Interesting, will try to fix it :)

**Comment by T8RIN** [comment]
I found workaround, PNG is a loseless format, so i can compress as JPEG and save it to you as PNG, will it be good for you? There is no alternatives, unfortunately :(

**Comment by T8RIN** [comment]
No, this is unreachable, i will remove quality picking for png format
