### ISSUE TITLE
Copycat/Clone of ImageResizer on Google Play

### ISSUE THREAD

**Issue by Poussinou** [T8RIN/ImageResizer#74]
Hi,

I just found this copycat of your app on Google Play https://play.google.com/store/apps/details?id=ru.tech.imageresizershrxcver from [this developer](https://play.google.com/store/apps/developer?id=Schnupfeld).

It's full of ads. It might be a violatiton of Apache V2 since I can't find the license and the changes he made to the app.

People from Newpipe wrote a procedure to report the app to Google Play that I collected [here](https://gist.github.com/Poussinou/86136151f8b939fbaa48650666bf62d6) in a gist if it's of some interest for you.

**Comment by T8RIN** [comment]
Oh, thanks, i think so i need to publish my app to gStore...

**Comment by marcoXbresciani** [comment]
The same happened to my app. (https://codeberg.org/marco.bresciani/TKCompanionApp/issues/24)

I wrote Google for copyright violation and they just replied they are going to remove the clone of my app.
Feel free to do the same.

**Comment by T8RIN** [comment]
Thanks!

**Comment by T8RIN** [comment]
I wrote at least two reports, but nothing happened, there are even no replies...(

**Comment by marcoXbresciani** [comment]
Strange. They replied me and acted in a few days.
Try the link I've been suggested: https://codeberg.org/marco.bresciani/TKCompanionApp/issues/24#issue-267642

**Comment by T8RIN** [comment]
I've exactly used that pattern (

**Comment by T8RIN** [comment]
It deleted!

**Comment by Poussinou** [comment]
Good news !

Please report it here if you find other copycats.
