### ISSUE TITLE
Dynamic color is broken

### ISSUE THREAD

**Issue by adarsh1001** [T8RIN/ImageResizer#75]
When navigating to any page from the homepage and then coming back, the color scheme changes to green which seems to be the default option under the "Color scheme" option, although this should be disabled as "Dynamic colors" option is enabled.

Video to showcase the issue:
https://user-images.githubusercontent.com/8820038/225447449-aa328117-1811-4343-8812-16e59501702e.mp4

**Comment by T8RIN** [comment]
Oh, thanks for the issue, i will fix it soon

**Comment by T8RIN** [comment]
Wait in the next release :)
