### ISSUE TITLE
[New Tool] Change Hue

### ISSUE THREAD

**Issue by xmha97** [T8RIN/ImageResizer#80]
Please add a new tool for changing hue:

https://user-images.githubusercontent.com/23485114/225627087-bd500407-a7b9-46aa-a947-9a623aafeac9.mp4

Thanks 🙏

**Comment by T8RIN** [comment]
I think this is not fit for Image Resizer app...

**Comment by T8RIN** [comment]
Maybe i will add this, thanks for the offer

**Comment by xmha97** [comment]
> I think this is not fit for Image Resizer app...

This app is more than just an image resizer and that's why I created issue #29.
And let me add that I have never once had to resize an image and I think the original size is the best size.
I have installed this app just to crop images.

**Comment by T8RIN** [comment]
It's more to shrink something 👀

**Comment by T8RIN** [comment]
I will do it, and also many filters :)

**Comment by xmha97** [comment]
> I will do it, and also many filters :)

Thankful
You may not believe it, but it was the happiest news I have heard in a while.

**Comment by T8RIN** [comment]
> > I will do it, and also many filters :)
> 
> Thankful
> You may not believe it, but it was the happiest news I have heard in a while.

:))

**Comment by T8RIN** [comment]
27 filters done

**Comment by T8RIN** [comment]
A little bit more than you requested 👀

**Comment by T8RIN** [comment]
@xmha97 Can you write me on telegram? I need someone, who can test if all works fine
