### ISSUE TITLE
Crash on Resize by weight

### ISSUE THREAD

**Issue by crashlyrics** [T8RIN/ImageResizer#91]
java.lang.NullPointerException
java.lang.NullPointerException
	at t8.d.a(SourceFile:168)
	at ru.tech.imageresizershrinker.main_screen.l.a0(SourceFile:19)
	at z7.b$a.j(SourceFile:231)
	at h6.a.v(Unknown Source:8)
	at z6.j0.run(Unknown Source:100)
	at kotlinx.coroutines.internal.f.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:79)
	Suppressed: m4.e: [o1{Cancelling}@f936221, Dispatchers.Main.immediate]

**Comment by T8RIN** [comment]
Additional info?

**Comment by crashlyrics** [comment]
Sorry, I'm no expert. What do you need? Happens on a moto g8 with Android 11 ...

**Comment by T8RIN** [comment]
Which size you picked, how many images were choosen, i.e how to reproduce the issue

**Comment by crashlyrics** [comment]
Picked first 500 then 400 KB. Original size about 5+ MB. Only one image. I used the feature before and it worked once. Now it doesn't any more.

**Comment by T8RIN** [comment]
At all, with any size of image?

**Comment by T8RIN** [comment]
Could you please check it on version 1.9.2 ?

**Comment by crashlyrics** [comment]
Sorry, I only tried what I told you. Don't know anything more ...

**Comment by crashlyrics** [comment]
It happened both first with previous version, then with the new one.

**Comment by T8RIN** [comment]
Null pointer in both times?

**Comment by crashlyrics** [comment]
What is this?

**Comment by T8RIN** [comment]
Type of exception, you send it in the first message 👀

**Comment by T8RIN** [comment]
i really don't get it, it's weird, the log says the error happened on the main screen... But not in bytes resize screen...

**Comment by crashlyrics** [comment]
Sorry for the inconvenience ... :)

**Comment by T8RIN** [comment]
no big deal, just figure out what the problem is 👀

**Comment by crashlyrics** [comment]
I'll try again some time. No urgent need right now. Thank you.

**Comment by T8RIN** [comment]
Ok, will wait :)
